labels = {
  regions: {
    "us": "United States",
    "il": "Israel",
    "gb": "United Kingdom",
    "de": "Germany",
    "fr": "France",
    "in": "India",
    "jp": "Japan",
    "cn": "China",
    "ru": "Russia",
    "br": "Brazil",
    "za": "South Africa",
    "au": "Australia",
    "ca": "Canada",
    "mx": "Mexico",
    "kr": "South Korea",
    "sa": "Saudi Arabia",
    "tr": "Turkey",
    "eg": "Egypt",
    "ar": "Argentina",
    "es": "Spain",
    "it": "Italy",
    "ng": "Nigeria",
    "ua": "Ukraine",
    "se": "Sweden",
    "no": "Norway",
    "fi": "Finland",
    "nl": "Netherlands",
    "ch": "Switzerland",
    "pk": "Pakistan",
    "id": "Indonesia",
    "pl": "Poland",
    "ro": "Romania",
    "ve": "Venezuela",
    "cl": "Chile",
    "th": "Thailand",
    "pt": "Portugal",
    "dk": "Denmark",
    "ie": "Ireland",
    "at": "Austria",
    "gr": "Greece",
    "hu": "Hungary",
    "be": "Belgium",
    "ae": "United Arab Emirates",
    "my": "Malaysia",
    "sg": "Singapore",
    "ph": "Philippines",
    "nz": "New Zealand",
    "co": "Colombia"
}
};